server:
  port: 8080

spring:
  application:
    name: gateflux
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2gw1uaqrtf1w7k5s.us.auth0.com/
  aerospike:
    hosts: localhost:3000
    namespace: test
    mock:
      enabled: false
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: my_first_route
              uri: https://httpbin.org
              predicates:
                - Path=/api/get/**
              filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"